### ISSUE TITLE
Duplicate class import collision when importing the Heartbeat Tool

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoAndroidTools#101]
When importing multiple Ditto Tools, an import collision occurs because the `BuildConfig` class is exposed by both tools.

Example:
```
Duplicate class live.ditto.health.BuildConfig found in modules dittohealthmetrics-1.0.0-runtime (live.ditto:dittohealthmetrics:1.0.0) and health-1.0.0-runtime (live.ditto:health:1.0.0)
```

**Comment by rajramsaroop** [comment]
Looks like the namespace for the `:DittoHealthMetrics` needs to be updated. I am thinking to `live.ditto.dittohealthmetrics`.

Would then need to make sure any other modules that are trying to use the `BuildConfig` class for health metrics is importing the correct one.

**Comment by bplattenburg** [comment]
> Looks like the namespace for the `:DittoHealthMetrics` needs to be updated. I am thinking to `live.ditto.dittohealthmetrics`.
> 
> Would then need to make sure any other modules that are trying to use the `BuildConfig` class for health metrics is importing the correct one.

Based on the discussion in #77 , I think we want it to be `live.ditto.healthmetrics` to avoid the redundant `ditto`

**Comment by rajramsaroop** [comment]
Damn, my PR is 102 and this issue is 101... So close xD

**Comment by rajramsaroop** [comment]
Noting here for visibility - PR merged, just need to update tools version and publish to maven.
