### ISSUE TITLE
Update dependencies for demo app

### ISSUE THREAD

**Issue by rajramsaroop** [getditto/DittoAndroidTools#104]
Today the demo app points to the local projects as some tools were not published to maven. 

We should update the dependencies in `build.gradle` of the demo app to point to the maven dependencies so it can be used as an up to date example of how to implement tools.

**Comment by okdistribute** [comment]
The original thinking for pointing the dependencies to be local is for development. It helped us iterate faster on testing changes in the tools

**Comment by rajramsaroop** [comment]
Currently there is a mix of some tools being pulled in from maven, others local. This would make it more consistent. There were also todo comments left for updating the imports to use maven as well.

If someone wanted to iterate and quickly test there's nothing to stop someone from commenting out the maven import and importing the local project. This works well for testing something in the demo app.

Zan also completed some work previously that allowed publishing to maven locally so that we can also test the tools changes locally in other projects, not just the tools project.

So even after these changes it's still very easy to use the local versions for testing and I like the idea of including something in the readme on how to do this. The steps themselves for both these options are simple and should take minutes to get up and running.
