### ISSUE TITLE
PV: Display peer count

### ISSUE THREAD

**Issue by byoung-ditto** [getditto/DittoAndroidTools#40]
Currently the Presence Viewer displays a graph is known direct and remote peers
For larger meshes it is challenging to determine from this view how many peers are in the mesh and makes when troubleshooting and/or viewing the PV for multiple device, this makes it hard to correlate one PV to the PV on another device

Recommend display the direct and remote peer counts along the bottom of the screen

**Comment by okdistribute** [comment]
Hi Brian!~ For Presence Viewer improvements, please move this ticket to `getditto/ditto` as the source is there.

**Comment by byoung-ditto** [comment]
OK will do, I see this is perhaps an older version of the PV code:
https://github.com/getditto/DittoAndroidTools/tree/main/DittoPresenceViewer
