### ISSUE TITLE
Android - Add schema version field to devices collection used by Heartbeat tool

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoAndroidTools#44]
Add a root-level property tracking the schema of the devices collection used by the heartbeat tool so that we can future proof it. Initially, that will look like:

`"_schema": "1"`

**Comment by rajramsaroop** [comment]
This is actually already done on Android so should be ok to close.

See [HeartbeatCollection.kt](https://github.com/getditto/POSHealth/blob/main/android/app/src/main/java/live/ditto/poshealth/data/collections/HeartbeatCollection.kt) for the relevant code.

**Comment by rajramsaroop** [comment]
Wait you mean in the Heartbeat tool itself, not the POS Health app, my bad!
