### ISSUE TITLE
Log Exporter - don't use a static id for fileprovider

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoAndroidTools#72]
Today, our log export tool uses a static ID for the content provider (fileprovider) in the Log Exporter tool, with no references to the host application. Because of this, you can't install 2 different apps on the same device that both include the Log Exporter tool.

Instead, we should make the ID dynamic based on the app the tool is used in, like something like $hostAppId + `live.ditto.dittotoolsapp.fileprovider`

**Comment by rajramsaroop** [comment]
Using the host app id is a suggestion, but one that makes the most sense (to me, open to more suggestions).

The particular entry in the `AndroidManifest.xml` is `android:authorities="live.ditto.dittotoolsapp.fileprovider"` - would have to look into how we can make that dynamic.
