### ISSUE TITLE
Setup CI to publish new versions automatically

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoAndroidTools#80]

**Comment by zmarkan** [comment]
Creds & package signing key are in 1password. 
Sync with @texasRanger09 and @rajramsaroop Wednesday 29 May

**Comment by zmarkan** [comment]
I've been having lots of trouble getting Gradle to sign and upload archives to Maven Central. 
Tried a few different signing plugins and approaches  with limited success. 
Syncing with Raj later today to see if he can spot something obvious I may have missed

**Comment by bplattenburg** [comment]
This can be closed, the work is done and being used today, but we missed closing the issue here.
