### ISSUE TITLE
Remove heartbeat collection subscription

### ISSUE THREAD

**Issue by bplattenburg** [getditto/DittoAndroidTools#84]
Today, we automatically subscribe any device using the hearbeat tool to the entire `dittotools_devices` collection, but that doesn't scale to production across multiple locations.

Instead, we want to make this "opt-in" by creating manual subscriptions do devices at the same location if desired, and remove the subscription from the tool itself

**Comment by okdistribute** [comment]
Should we even create any subscriptions as part of this tool at all? Seems a bit like magic that should be user controlled.

The heartbeat tool could be a simple way to get data out on an interval. It doesn't need to subscribe to anything to function.

**Comment by bplattenburg** [comment]
@okdistribute It's definitely worth some more discussions. The original intent was to allow multi-hop to get the data out for devices that couldn't directly connect to the Big Peer, but that requires some level of scoping to subscribe only to devices at the same physical location.
