### ISSUE TITLE
Add the ability to publish to Maven locally

### ISSUE THREAD

**Issue by rajramsaroop** [getditto/DittoAndroidTools#90]
Being able to publish locally will allow developers to import their local changes into other Android projects locally that are outside the tools repo. This is useful as it allows developers to properly test their changes.

Right now if you try to run `./gradlew publishToMavenLocal` you run into signing issues. Let's fix that and any other issues that might arise so that we can publish locally.

**Comment by zmarkan** [comment]
That's a good shout.
The place to look would be the `signing` block in `gradle/deploy.gradle` - needs to omit anything apart from the maven release build triggers.
